name: Deploy Application

on:
  push:
    branches:
      - main  # Ana branch üzerine push yapıldığında çalıştır

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run application
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
        RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      run: |
        python app.py
